---
permalink: rhel-install/task-back-up-regular-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, back up, regular, wfa database, cli 
summary: 'Sie können ein regelmäßiges Backup der OnCommand Workflow Automation (WFA) Datenbank mithilfe der WFA Befehlszeilenschnittstelle (CLI) durchführen. In einem regelmäßigen Backup wird nur die WFA Datenbank gesichert.' 
---
= Sichern Sie die WFA Datenbank mithilfe der CLI (regelmäßig)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein regelmäßiges Backup der OnCommand Workflow Automation (WFA) Datenbank mithilfe der WFA Befehlszeilenschnittstelle (CLI) durchführen. In einem regelmäßigen Backup wird nur die WFA Datenbank gesichert.

Sie müssen über Anmeldedaten für Admin-Benutzer, Anmeldeinformationen für Architektur oder Sicherungsbenutzer verfügen.

In einer Hochverfügbarkeitsumgebung sollten geplante Backups mithilfe VON REST APIs erstellt werden. Sie können keine Backups über die CLI erstellen, wenn WFA sich im Failover-Modus befindet.

Weitere Informationen finden Sie in DER REST-Dokumentation.

.Schritte
. Navigieren Sie an der Shell-Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server: WFA_install_location/wfa/bin/.
+
WFA_install_location ist das WFA Installationsverzeichnis.

. Backup der WFA Datenbank: `.\wfa --backup --user=USER [--password=PASS] [--location=PATH]`
+
** Benutzer ist der Benutzername des Backup-Benutzers.
** Passwort ist das Passwort des Backup-Benutzers.
+
Falls Sie kein Passwort angegeben haben, müssen Sie das Passwort eingeben, wenn Sie dazu aufgefordert werden.

** Der Pfad ist der vollständige Verzeichnispfad zur Sicherungsdatei.


. Vergewissern Sie sich, dass die Sicherungsdatei am angegebenen Speicherort erstellt wurde.

