---
permalink: rhel-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication, settings 
summary: 'Sie können OnCommand Workflow Automation (WFA) konfigurieren, um einen Microsoft Active Directory (AD) LDAP-Server (Lightweight Directory Access Protocol) zur Authentifizierung und Autorisierung zu verwenden.' 
---
= Konfigurieren Sie die Authentifizierungseinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können OnCommand Workflow Automation (WFA) konfigurieren, um einen Microsoft Active Directory (AD) LDAP-Server (Lightweight Directory Access Protocol) zur Authentifizierung und Autorisierung zu verwenden.

Sie müssen einen Microsoft AD LDAP-Server in Ihrer Umgebung konfiguriert haben.

Für WFA wird nur die Microsoft AD-LDAP-Authentifizierung unterstützt. Sie können keine anderen LDAP-Authentifizierungsmethoden verwenden, einschließlich Microsoft AD Lightweight Directory Services (AD LDS) oder Microsoft Global Catalog.


NOTE: Während der Kommunikation sendet LDAP den Benutzernamen und das Passwort im Klartext. Allerdings ist die Kommunikation mit LDAPS (LDAP Secure) verschlüsselt und sicher.

.Schritte
. Melden Sie sich über einen Webbrowser als Administrator bei WFA an.
. Fügen Sie den erforderlichen Rollen eine Liste mit Active Directory-Gruppennamen hinzu.
+

NOTE: Im Fenster „Active Directory Groups“ können Sie den erforderlichen Rollen eine Liste mit AD-Gruppennamen hinzufügen.

+
xref:task-add-active-directory-group-names.adoc[Active Directory Groups -Fenster]

. Klicken Sie auf *Administration* > *WFA Konfiguration*.
. Klicken Sie im Dialogfeld WFA Configuration auf die Registerkarte *Authentifizierung* und aktivieren Sie dann das Kontrollkästchen *Active Directory aktivieren*.
. Geben Sie die erforderlichen Informationen in die folgenden Felder ein:
+
.. Wenn Sie das Domain-Format des Benutzers@für Domain-Benutzer verwenden möchten, ersetzen Sie sAMAccountName im Feld *User Name attribut* durch userPrincipalName.
.. Wenn für Ihre Umgebung eindeutige Werte erforderlich sind, bearbeiten Sie die erforderlichen Felder.


. Klicken Sie auf *Hinzufügen*, um das Active Directory in der Tabelle Active Directory Servers mit einem URI-Format hinzuzufügen: `ldap://active_directory_server_address\[:port\]`
+
ldap://NB-T01.example.com[:389]

+
Wenn Sie LDAP über SSL aktiviert haben, können Sie das folgende URI-Format verwenden: `ldaps://active_directory_server_address\[:port\]`

. Geben Sie die Anmeldeinformationen an, um den LDAP-Server und den Basis-DN zu binden.
. Testen Sie die Authentifizierung des angegebenen Benutzers:
+
.. Geben Sie den Benutzernamen und das Kennwort ein.
.. Klicken Sie Auf *Authentifizierung Testen*.


+

NOTE: Sie müssen die Active Directory-Gruppe hinzugefügt haben, um die Authentifizierung des angegebenen Benutzers in WFA zu testen.

. Klicken Sie Auf *Speichern*.

