---
permalink: rhel-install/task-back-up-the-wfa-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: back up, restore, oncommand, workflow, automation, database, configurations, linux 
summary: 'Sie können eine Backup- und Restore-Erstellung für die OnCommand Workflow Automation (WFA) Datenbank und unterstützte Konfigurationen erstellen, damit Sie die Daten bei einem Ausfall wiederherstellen können. Zu den unterstützten Konfigurationen gehören Datenzugriff, HTTP Timeout und SSL-Zertifikate.' 
---
= Sichern Sie die OnCommand Workflow Automation-Datenbank und -Konfigurationen unter Linux und stellen Sie sie wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Backup- und Restore-Erstellung für die OnCommand Workflow Automation (WFA) Datenbank und unterstützte Konfigurationen erstellen, damit Sie die Daten bei einem Ausfall wiederherstellen können. Zu den unterstützten Konfigurationen gehören Datenzugriff, HTTP Timeout und SSL-Zertifikate.

Sie müssen über Administratorrechte oder Anmeldedaten zum Erstellen verfügen.

Sie müssen das Backup an einem sicheren Ort erstellen, da die Wiederherstellung des Backups Zugriff auf alle Storage-Systeme bietet, auf die WFA zugegriffen hat.

[NOTE]
====
* Während der Disaster Recovery ist ein umfassendes Backup von WFA Datenbanken und Konfigurationen erforderlich und kann sowohl in Standalone- als auch in Hochverfügbarkeitsumgebungen eingesetzt werden.
* Im Disaster Recovery können nur die CLI-Befehle oder REST-APIs für umfassende Backup- und Restore-Vorgänge verwendet werden.
+
Sie können die Web-Benutzeroberfläche nicht zum Sichern oder Wiederherstellen der WFA Datenbank während eines Disaster Recovery verwenden.



====
.Schritte
. Sichern der OnCommand Workflow Automation-Datenbank.
+
link:reference-backing-up-of-the-oncommand-workflow-automation-database.html["Backup der OnCommand Workflow Automation-Datenbank"]

. Wiederherstellen eines früheren Backups der OnCommand Workflow Automation-Datenbank.
+
link:concept-restoring-the-wfa-database.html["Wiederherstellen der OnCommand Workflow Automation-Datenbank"]


