---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Falls Sie das Passwort des Admin-Benutzers, den Sie beim Installieren des OnCommand Workflow Automation (WFA) Servers erstellt haben, vergessen haben, können Sie ihn zurücksetzen.' 
---
= Setzt das bei der Installation erstellte Admin-Passwort zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie das Passwort des Admin-Benutzers, den Sie beim Installieren des OnCommand Workflow Automation (WFA) Servers erstellt haben, vergessen haben, können Sie ihn zurücksetzen.

* Sie müssen Root-Rechte für das Linux-System besitzen, auf dem WFA installiert ist.
* Die WFA Services müssen ausgeführt werden.
* Bei diesem Verfahren wird nur das Passwort des während der WFA Installation erstellten Admin-Benutzers zurückgesetzt.
+
Sie können das Passwort anderer WFA Admin-Benutzer, die Sie nach der WFA Installation erstellt haben, nicht zurücksetzen.

* Durch diese Vorgehensweise wird die Passwortrichtlinie, die Sie konfiguriert haben, nicht durchgesetzt.
+
Deshalb müssen Sie ein Passwort eingeben, das Ihrer Passwortrichtlinie entspricht, oder das Passwort von der WFA Benutzeroberfläche ändern, nachdem Sie das Passwort zurückgesetzt haben.



.Schritte
. Melden Sie sich als Root-Benutzer beim Linux-System an, auf dem WFA installiert ist.
. Navigieren Sie an der Shell-Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server: WFA_install_location/wfa/bin/
. Geben Sie den folgenden Befehl ein:
+
`./wfa --admin-password [--password=PASS]`

+
Falls Sie kein Passwort angegeben haben, müssen Sie das Passwort bei der entsprechenden Eingabeaufforderung eingeben.

. Folgen Sie an der Shell-Eingabeaufforderung den Anweisungen auf dem Bildschirm.

