---
permalink: rhel-install/task-upgrade-from-wfa-4-2.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, upgrade, later 
summary: 'Sie können ein Upgrade von OnCommand Workflow Automation (WFA) 3.1 oder höher auf die neueste verfügbare Version von WFA durchführen, um die neuen Funktionen und Verbesserungen zu nutzen.' 
---
= Upgrade von OnCommand Workflow Automation 3.1 oder höher
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von OnCommand Workflow Automation (WFA) 3.1 oder höher auf die neueste verfügbare Version von WFA durchführen, um die neuen Funktionen und Verbesserungen zu nutzen.

Sie müssen die Binärdatei .bin von der NetApp Support Site auf die WFA Host Machine heruntergeladen haben.

Sie können nur von WFA 5.0 oder 4.2 aus auf WFA 5.1 wiederherstellen. Ein Backup von WFA Datenbanken kann nur auf einem System wiederhergestellt werden, auf dem dieselbe oder eine höhere Version von WFA ausgeführt wird.

Die WFA 5.1-Cluster-Verbindung muss das SSL-Zertifikat akzeptieren. Beim Update von einer früheren Version von WFA auf WFA 5.1 müssen Sie die Cluster-Verbindung zertifizieren. Speichern Sie nach dem vorhandenen Upgrade die Cluster-Verbindungsdetails für die Cluster-Zertifizierung.

SIE können MYSQL beim Upgrade von älteren WFA Versionen nicht eigenständig installieren. Sie können MySQL selbst installieren:

* Wenn Sie ein Upgrade von WFA 4.2 auf neuere Versionen von WFA durchführen.
* Upgrade von WFA 3.1 oder höher durch Auswahl einer der folgenden Methoden:
+
** Interaktive Installation
+
... Navigieren Sie auf dem WFA Host Machine zur .bin-Binärdatei und führen Sie die Datei anschließend aus.
... Befolgen Sie die Anweisungen auf dem Bildschirm, um die Aktualisierung abzuschließen.


** Automatische Installation
+
An der Shell-Eingabeaufforderung:

+
`./WFA-version_number-build_number.bin [-y] [-u admin_user_name] [-p admin_user_password]`

+
*Beispiel:*

+
`./WFA-3.1-Z3234343435.bin -y -u admin -p Company*234`

+
Während der automatischen Aktualisierung müssen Sie Werte für alle der folgenden Befehlsoptionen enthalten:

+
*** `-y` Überspringt die Installationsbestätigung.
*** `-u` Gibt den Admin-Benutzernamen an.
*** `-p` Gibt das Admin-Benutzerpasswort an.
+
Wenn Sie das Admin-Benutzerpasswort nicht angegeben haben, müssen Sie bei der entsprechenden Eingabeaufforderung das Passwort eingeben.






