---
permalink: windows-install/task-reset-the-admin-password-created-during-installation.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Falls Sie das Passwort des Admin-Benutzers vergessen haben, den Sie bei der Installation des OnCommand Workflow Automation-Servers (WFA) erstellt haben, können Sie das Passwort zurücksetzen.' 
---
= Setzt das bei der Installation erstellte Admin-Passwort zurück
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie das Passwort des Admin-Benutzers vergessen haben, den Sie bei der Installation des OnCommand Workflow Automation-Servers (WFA) erstellt haben, können Sie das Passwort zurücksetzen.

* Sie müssen über Administratorrechte für das Windows System verfügen, auf dem WFA installiert ist.
* Die WFA Services müssen ausgeführt werden.
* Bei diesem Verfahren wird nur das Passwort des Admin-Benutzers zurückgesetzt, der während der WFA Installation erstellt wurde.
+
Sie können das Passwort anderer WFA Admin-Benutzer, die Sie nach der WFA Installation erstellt haben, nicht zurücksetzen.

* Durch diese Vorgehensweise wird die Passwortrichtlinie, die Sie konfiguriert haben, nicht durchgesetzt.
+
Sie müssen entweder ein Passwort eingeben, das zu Ihrer Passwortrichtlinie entspricht, oder das Passwort von der WFA Benutzeroberfläche ändern, nachdem Sie das Passwort zurückgesetzt haben.



.Schritte
. Öffnen Sie eine Eingabeaufforderung, und navigieren Sie zum folgenden Verzeichnis: `WFA_install_location\WFA\bin\`
. Geben Sie den folgenden Befehl ein:
+
`wfa --admin-password [--password=PASS]`

+
Wenn Sie das Passwort im Befehl nicht angeben, müssen Sie bei der entsprechenden Eingabeaufforderung das Passwort eingeben.

. Befolgen Sie an der Eingabeaufforderung die Anweisungen auf dem Bildschirm, um das Admin-Passwort zurückzusetzen.

