---
permalink: windows-install/task-disable-the-default-password-policy.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) ist so konfiguriert, dass eine Passwortrichtlinie für lokale Benutzer durchgesetzt wird. Wenn Sie die Passwortrichtlinie nicht verwenden möchten, können Sie sie deaktivieren.' 
---
= Deaktivieren Sie die Standard-Passwortrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) ist so konfiguriert, dass eine Passwortrichtlinie für lokale Benutzer durchgesetzt wird. Wenn Sie die Passwortrichtlinie nicht verwenden möchten, können Sie sie deaktivieren.

Sie müssen als Administrator beim WFA Host-System angemeldet sein.

In diesem Verfahren wird der WFA Standardinstallationspfad verwendet. Wenn Sie während der Installation den Standardspeicherort geändert haben, müssen Sie den geänderten WFA Installationspfad verwenden.

.Schritte
. Öffnen Sie Windows Explorer und navigieren Sie zum folgenden Verzeichnis: `WFA_install_location\WFA\bin\.`
. Doppelklicken Sie auf die Datei ps.cmd.
+
Es wird eine PowerShell Eingabeaufforderung für die Befehlszeilenschnittstelle (CLI) geöffnet, wobei ONTAP- und WFA-Module enthalten sind.

. Geben Sie an der Eingabeaufforderung Folgendes ein:
+
`Set-WfaConfig -Name PasswordPolicy -Enable $false`

. Starten Sie die WFA Services nach der entsprechenden Aufforderung neu.

