---
permalink: windows-install/task-upgrade-mysql-on-windows-wfa.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, upgrade mysql 
summary: 'Sie können neue Versionen von MySQL für OnCommand Workflow Automation (WFA) auf dem Windows Server aktualisieren. Sie können ein Upgrade auf eine neuere Version von MySQL durchführen, um auf dem Windows-Server Sicherheitslücken zu finden.' 
---
= MySQL aktualisieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können neue Versionen von MySQL für OnCommand Workflow Automation (WFA) auf dem Windows Server aktualisieren. Sie können ein Upgrade auf eine neuere Version von MySQL durchführen, um auf dem Windows-Server Sicherheitslücken zu finden.

Sie müssen über die Administratorrechte für Windows und das Passwort für DEN MYSQL Root-Benutzer auf dem WFA Server verfügen.


NOTE: Vor der Neuinstallation von WFA 4.2 oder neuer müssen Sie das MySQL-Datenverzeichnis gelöscht haben, wenn Sie MySQL deinstalliert haben.

Sie sollten die folgenden Einschränkungen beachten:

* Sie können ein Upgrade in einer beliebigen Version von MySQL 5.7 durchführen.
+
Sie können beispielsweise ein Upgrade von MySQL 5.7.1 auf MySQL 5.7 durchführen.

* Sie können kein Upgrade von MySQL 5.7 auf MySQL 5.8 durchführen


.Schritte
. Melden Sie sich als Admin-Benutzer auf der WFA Host Machine an.
. Laden Sie die entsprechende Version von MySQL auf das Zielsystem herunter.
. Verwenden Sie die Windows Services-Konsole, um die folgenden WFA-Services zu beenden:
+
** NetApp WFA Database oder MYSQL57
** NetApp WFA Server


. Klicken Sie auf DAS MYSQL msi Paket, um das Upgrade von MySQL aufzurufen.
. Befolgen Sie die Anweisungen auf dem Bildschirm, um die MySQL-Installation abzuschließen.
. Starten Sie die WFA Services über die Windows Services Konsole.

