---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password policy, windows 
summary: 'OnCommand Workflow Automation (WFA) erzwingt lokale Benutzer durch ein Passwort. Sie können die Standard-Passwortrichtlinie ändern, um ein Kennwort gemäß Ihrer Anforderung festzulegen.' 
---
= Ändern Sie die Standard-Passwortrichtlinie für Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) erzwingt lokale Benutzer durch ein Passwort. Sie können die Standard-Passwortrichtlinie ändern, um ein Kennwort gemäß Ihrer Anforderung festzulegen.

Sie müssen als Root-Benutzer beim WFA Host-System angemeldet sein.

* In diesem Verfahren wird der WFA Standardinstallationspfad verwendet.
+
Wenn Sie während der Installation den Standardspeicherort geändert haben, müssen Sie auch den benutzerdefinierten WFA Installationspfad verwenden.

* Der Befehl zum Ändern der Standard-Passwortrichtlinie ist .\wfa --password-Policy=default.
+
Die Standardeinstellung ist "`minLength=true,8;specialChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whespaceChar=false`". Gemäß dieser Einstellung für die Standard-Passwortrichtlinie muss das Passwort eine Mindestlänge von acht Zeichen aufweisen, mindestens ein Sonderzeichen, eine Ziffer, ein Kleinbuchstaben und ein Großbuchstaben enthalten und darf keine Leerzeichen enthalten.



.Schritte
. Navigieren Sie an der Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server:
+
`WFA_install_location/wfa/bin/`

. Ändern Sie die Standard-Passwortrichtlinie:
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`


