---
permalink: windows-install/task-manage-site-specific-perl-modules.html 
sidebar: sidebar 
keywords: manage, site-specific, perl modules 
summary: 'Sie können den ActiveState Perl Package Manager (PPM) verwenden, um Ihre standortspezifischen Perl-Module zu verwalten. Sie müssen Ihre standortspezifischen Perl-Module außerhalb des WFA Installationsverzeichnisses (OnCommand Workflow Automation) installieren, um das Löschen Ihrer Perl-Module während eines WFA Upgrades zu vermeiden.' 
---
= Standortspezifische Perl-Module verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den ActiveState Perl Package Manager (PPM) verwenden, um Ihre standortspezifischen Perl-Module zu verwalten. Sie müssen Ihre standortspezifischen Perl-Module außerhalb des WFA Installationsverzeichnisses (OnCommand Workflow Automation) installieren, um das Löschen Ihrer Perl-Module während eines WFA Upgrades zu vermeiden.

Mithilfe der Umgebungsvariable PERL5LIB können Sie den Perl-Interpreter konfigurieren, der auf dem WFA Server installiert ist, um Ihre Perl-Module zu verwenden.

Die Installation des Try-Tiny Perl Moduls im Benutzerbereich bei c:\Perl wird in diesem Verfahren als Beispiel verwendet. Dieser Benutzerbereich wird bei der Deinstallation von WFA nicht gelöscht, und Sie können den Bereich nach der Neuinstalliert oder einem Upgrade von WFA wiederverwenden.

.Schritte
. Stellen Sie die Umgebungsvariable PERL5LIB auf den Speicherort ein, an dem Sie Ihre Perl-Module installieren möchten.
+
`c:\>echo %PERL5LIB%` `c:\Perl`

. Vergewissern Sie sich, dass der Perl-Modulbereich nicht mit initialisiert wurde `ppm area list`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│ (user) │  n/a │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. Initialisieren Sie den Perl-Modulbereich mithilfe von `ppm area init user`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area init user`

+
[listing]
----
Syncing user PPM database with .packlists...done
----
. Überprüfen Sie, ob der Perl-Modulbereich mit initialisiert wird `ppm area list`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│  user  │  0   │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. Fügen Sie die erforderlichen Repositories hinzu und installieren Sie die erforderlichen Pakete.
+
.. Fügen Sie das erforderliche Repository mit hinzu `ppm repo add`.
+
`+c:\Program Files\NetApp\WFA\Perl64\bin>ppm repo add http://ppm4.activestate.com/MSWin32-x64/5.16/1600/package.xml+`

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Repo 1 added.
----
.. Überprüfen Sie, ob das erforderliche Repository mit hinzugefügt wird `ppm repo list`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm repo list`

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ id     │ pkgs │ name                                           │
├────────┼──────┼────────────────────────────────────────────────┤
│  1     │17180 │ ppmr.activestate.com                           │
└────────┴──────┴────────────────────────────────────────────────┘
 (1 enabled repository)
----
.. Installieren Sie das erforderliche Perl-Modul mithilfe von `ppm install`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm install Try-Tiny --area user`

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Downloading Try-Tiny-0.18...done
Unpacking Try-Tiny-0.18...done
Generating HTML for Try-Tiny-0.18...done
Updating files in user area...done
   2 files installed
----
.. Überprüfen Sie, ob das erforderliche Perl-Modul mithilfe von installiert ist `ppm area list`.
+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                            │
├────────┼──────┼────────────────────────────────────────────────┤
│  user  │  1   │ C:/Perl                                        │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib    │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib         │
└────────┴──────┴────────────────────────────────────────────────┘
----



