---
permalink: windows-install/task-upgrade-from-oncommand-workflow-automation-3-1-or-later-on-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, upgrade, later versions 
summary: 'Sie können ein Upgrade von OnCommand Workflow Automation (WFA) 3.1 oder höheren Versionen auf die aktuellen Versionen von WFA durchführen, um die neuen Funktionen und Verbesserungen zu nutzen.' 
---
= Upgrade von OnCommand Workflow Automation 3.1 oder höheren Versionen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von OnCommand Workflow Automation (WFA) 3.1 oder höheren Versionen auf die aktuellen Versionen von WFA durchführen, um die neuen Funktionen und Verbesserungen zu nutzen.

Sie müssen die .exe-Binärdatei von der NetApp Support Site auf die WFA Host Machine heruntergeladen haben.

Die WFA 5.1-Cluster-Verbindung muss das SSL-Zertifikat akzeptieren. Beim Update von einer früheren Version von WFA auf WFA 5.1 müssen Sie die Cluster-Verbindung zertifizieren. Speichern Sie nach dem vorhandenen Upgrade die Cluster-Verbindungsdetails für die Cluster-Zertifizierung.

Sie können MySQL beim Upgrade von älteren WFA Versionen nicht eigenständig installieren. Sie können MySQL jedoch selbst installieren:

* Während einer Neuinstallation von WFA 4.2 und höher oder
* Wenn Sie ein Upgrade von WFA 4.2 auf neuere Versionen von WFA durchführen.


.Schritt
. Upgrade von WFA 3.1 oder höheren Versionen durch Auswahl einer der folgenden Methoden:
+
** Interaktive Installation
+
... Navigieren Sie zur .exe-Binärdatei auf dem WFA-Hostcomputer und führen Sie die Datei aus.
... Befolgen Sie die Anweisungen auf dem Bildschirm im Assistenten, um die Aktualisierung abzuschließen.


** Automatische Installation
+
Geben Sie an der Eingabeaufforderung Folgendes ein:

+
`WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME_UP=wfa username WFA_ADMIN_PASSWORD_UP=password /qr /l*v C:\upgrade.log"`

+
* Beispiel*:

+
`WFA-x64-v4.2.0.0.0-B2973881.exe /s /v"WFA_ADMIN_USERNAME_UP=admin WFA_ADMIN_PASSWORD_UP=password*123 /qr /l*v C:\upgrade.log"`

+

NOTE: Die /qn Option wird von WFA nicht unterstützt.

+
Wenn Sie ein unbeaufsichtigte Upgrade durchführen möchten, müssen Sie Werte für alle Befehlsparameter enthalten:

+
*** WFA_ADMIN_USERNAME_UP ist der Benutzername eines WFA Benutzers, der über die Berechtigung zum Erstellen eines WFA Datenbank-Backups verfügt.
*** WFA_ADMIN_PASSWORD_UP ist das Passwort des Benutzers.





