---
permalink: help/reference-edit-user-dialog-box.html 
sidebar: sidebar 
keywords: edit, user, dialog box, enable, view, modify, account, settings 
summary: Im Dialogfeld Benutzer bearbeiten können Sie Benutzerkontoeinstellungen anzeigen und ändern. 
---
= Dialogfeld „Benutzer bearbeiten“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Benutzer bearbeiten können Sie Benutzerkontoeinstellungen anzeigen und ändern.

Je nach Ihren Kontoberechtigungen und Rollen haben Sie möglicherweise keinen Zugriff auf das Fenster „Benutzer“. Sie können jedoch die Einstellungen für Ihr Konto bearbeiten, indem Sie *Einstellungen* wählen und unter *Verwaltung* auf *Kontoeinstellungen* klicken.


NOTE: Die Felder, die Ihnen zur Bearbeitung zur Verfügung stehen, hängen von Ihrer zugewiesenen Rolle und Ihren Kontoberechtigungen ab.

* *Name*
+
Zeigt den Benutzernamen für das Benutzerkonto an.

* * Rolle*
+
Zeigt die zugewiesene Rolle für das Benutzerkonto an.

* *E-Mail*
+
Gibt die E-Mail für das Benutzerkonto an, an die Benachrichtigungen gesendet werden, wenn die Option „Benachrichtigung bei“ ausgewählt ist.

* *Passwort ändern*
+
Ermöglicht Ihnen das Ändern des aktuellen Kennworts für das Benutzerkonto. Wenn dieses Kontrollkästchen aktiviert ist, sind folgende Felder erforderlich:

+
** *Neues Passwort*--gibt das neue Passwort an.
** *Bestätigen*--gibt das neue Passwort erneut an.


* *Benachrichtigen Sie Am*
+
Hiermit können Sie auswählen, wann der Account-Benutzer während der Ausführung des Workflows per E-Mail benachrichtigt werden soll. Wenn dieses Kontrollkästchen aktiviert ist, können Sie eine beliebige Kombination der folgenden Optionen auswählen:

+
** Workflow-Ausführung gestartet: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung beginnt.
** Workflow-Ausführung fehlgeschlagen/teilweise erfolgreich: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung fehlschlägt oder der Workflow erfolgreich ausgeführt wurde, selbst wenn ein oder mehrere Schritte fehlgeschlagen sind.
+
Die Ausführung ist abgeschlossen, weil die fehlgeschlagenen Schritte so konfiguriert wurden, dass die Workflow-Ausführung auch nach einem fehlgeschlagenen Schritt fortgesetzt wird.

** Workflow-Ausführung erfolgreich abgeschlossen: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung erfolgreich abgeschlossen wurde.
** Workflow-Ausführung wartet auf Genehmigung: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung abhängig von der WFA Konfigurationseinstellung auf Genehmigung durch einen Operator oder einen Architect wartet.
** Erfassungsfehler: Benachrichtigt den Benutzer, wenn die Datenerfassung für Datenquellen fehlschlägt.
+
Diese Option ist nur für Administrator- und Architect-Benutzer aktiviert.







== Befehlsschaltflächen

* *Speichern*
+
Speichert die Konfigurationseinstellungen und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht ggf. Änderungen ab und schließt das Dialogfeld.


