---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: Im Dialogfeld Anmeldeinformationen bearbeiten können Sie vorhandene Anmeldedaten ändern. 
---
= Dialogfeld „Anmeldeinformationen bearbeiten“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Anmeldeinformationen bearbeiten können Sie vorhandene Anmeldedaten ändern.



== Anmeldeinformationsparameter

* * Match*
+
Ermöglicht Ihnen die Auswahl des Match-Typs der Anmeldeinformationen, der die Anmeldeinformationen für eine bestimmte IP-Adresse oder einen Hostnamen oder einen gesamten Subnetz- oder IP-Bereich definiert. Zu den verfügbaren Optionen gehören:

+
** Exact: Definiert eine bestimmte IP-Adresse oder einen bestimmten Hostnamen
** Muster: Definiert ein gesamtes Subnetz oder einen IP-Bereich


* *Typ*
+
Ermöglicht Ihnen die Auswahl des Anmeldeinformationstyps aus der Dropdown-Liste.

+
VMware vCenter wird für Linux nicht unterstützt.

* *Name/IP*
+
Ermöglicht die Angabe des Host-Namens oder der IP-Adresse für die Anmeldedaten.

* *Benutzername*
+
Ermöglicht die Angabe des Benutzernamens für die Anmeldedaten.

* *Passwort*
+
Ermöglicht die Angabe des Passworts für den Benutzernamen.

* *Standardwerte Überschreiben*
+
Ermöglicht es Ihnen, die Standardwerte des Protokolls, Ports und Timeout zu überschreiben, die dem ausgewählten Remote-Systemtyp für die Anmeldedaten zugeordnet sind.

+
Standardmäßig ist dieses Kontrollkästchen nicht aktiviert. Sie müssen das Kontrollkästchen aktivieren, wenn Sie die Standardwerte überschreiben möchten.





== Protokolltabelle

In der Protokolltabelle werden die Portnummern und die Zeitüberschreitungsgrenzen (in Sekunden) für Protokolle angezeigt, die dem ausgewählten Remote-System für die Anmeldedaten zugeordnet sind.



== Befehlsschaltflächen

* *Test*
+
Ermöglicht Ihnen, die Verbindung zum Hostnamen oder zur IP-Adresse zu testen, indem Sie sich mit den erforderlichen Anmeldedaten anmelden.

* *Speichern*
+
Speichert die Konfigurationseinstellungen und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht die Änderungen ggf. ab und schließt das Dialogfeld.


