---
permalink: help/reference-new-user-dialog-box.html 
sidebar: sidebar 
keywords: new, user, dialog box, enable, create, account 
summary: Im Dialogfeld Neuer Benutzer können Sie ein neues Benutzerkonto erstellen. 
---
= Dialogfeld „Neuer Benutzer“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Neuer Benutzer können Sie ein neues Benutzerkonto erstellen.

* *Benutzername*
+
Gibt den Benutzernamen an.

* * Rolle*
+
Ermöglicht Ihnen die Auswahl einer der folgenden Benutzerrollen:

+
** Gast: Dieser Benutzer kann nur den Status einer Workflow-Ausführung anzeigen oder über eine Änderung des Status einer Workflow-Ausführung benachrichtigt werden.
** Operator: Dieser Benutzer darf Workflows anzeigen und ausführen, für die der Benutzer Zugriff erhält.
** Architekt: Dieser Benutzer hat vollen Zugriff auf die Erstellung von Workflows, ist aber durch das Ändern globaler WFA Servereinstellungen eingeschränkt.
** Admin: Dieser Benutzer hat vollständigen Zugriff auf den WFA Server.
** Backup: Dieser Benutzer ist der einzige Benutzer, der aus der Ferne Backups des WFA Servers generieren kann; der Benutzer ist jedoch von allen anderen Zugriffsrechten eingeschränkt.


* *E-Mail*
+
Hiermit können Sie die E-Mail-Adresse des Benutzers angeben, an die Benachrichtigungen gesendet werden, wenn die Option „Benachrichtigung ein“ ausgewählt ist.

* *Passwort*
+
Gibt das Kennwort für den Benutzer an.

* *Bestätigen*
+
Gibt das Kennwort erneut an.

* *Benachrichtigen Sie Am*
+
Hiermit können Sie auswählen, wann der Kontobenutzer per E-Mail benachrichtigt werden soll. Die Benachrichtigungen zum Workflow-Ausführungsstatus sind spezifisch für die vom Benutzer ausgeführten Workflows. Sie können eine beliebige Kombination der folgenden Optionen auswählen:

+
** Workflow-Ausführung gestartet: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung beginnt.
** Workflow-Ausführung fehlgeschlagen/teilweise erfolgreich: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung fehlschlägt oder der Workflow erfolgreich ausgeführt wurde, selbst wenn ein oder mehrere Schritte fehlgeschlagen sind.
+
Die Ausführung ist abgeschlossen, weil die fehlgeschlagenen Schritte so konfiguriert wurden, dass die Workflow-Ausführung auch nach einem fehlgeschlagenen Schritt fortgesetzt wird.

** Workflow-Ausführung erfolgreich abgeschlossen: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung erfolgreich abgeschlossen wurde.
** Workflow-Ausführung wartet auf Genehmigung: Benachrichtigt den Benutzer, wenn die Workflow-Ausführung abhängig von der WFA Konfigurationseinstellung auf Genehmigung durch einen Operator oder einen Architect wartet.
** Erfassungsfehler: Benachrichtigt den Benutzer, wenn die Datenerfassung für Datenquellen fehlschlägt.
+
Diese Option ist nur für Administrator- und Architect-Benutzer aktiviert.







== Befehlsschaltflächen

* *Speichern*
+
Speichert die Konfigurationseinstellungen und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht ggf. Änderungen ab und schließt das Dialogfeld.


