---
permalink: help/reference-clone-finder-dialog-box.html 
sidebar: sidebar 
keywords: clone, finder, dialog box, enable, create, copy, finder, edit 
summary: Im Dialogfeld Clone Finder können Sie eine Kopie des Finder erstellen und den geklonten Finder bearbeiten. 
---
= Dialogfeld „Clone Finder“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Clone Finder können Sie eine Kopie des Finder erstellen und den geklonten Finder bearbeiten.

* Registerkarte Eigenschaften
* Filter
* Registerkarte Attribute zurückgegeben




== Registerkarte Eigenschaften

Auf der Registerkarte Eigenschaften können Sie den Namen des Suchers, den Objekttyp und die Beschreibung des Suchers bearbeiten. Auf der Registerkarte werden auch die Eingabeparameter des im Finder verwendeten Filters angezeigt.

* *Name*
+
Ermöglicht das Bearbeiten des Namens des Suchers. Der Name des Suchers, den Sie zum Klonen ausgewählt haben, wird als Name für den Klon verwendet und mit angehängt `- copy` Standardmäßig.

* *Typ*
+
Ermöglicht die Auswahl des Objekttyps aus der Liste. Die Filter für das ausgewählte Objekt werden auf der Registerkarte Filter angezeigt.

* *Entity Version*
+
Ermöglicht die Eingabe der Versionsnummer für den Finder in `major.minor.revision` Format – z. B. 1.0.0.

* *Beschreibung*
+
Ermöglicht das Bearbeiten der Beschreibung für den Finder.

* *Eingabeparameter-Tabelle*
+
Zeigt die Eingabeparameter der ausgewählten Filter an.





== Registerkarte Filter

Ermöglicht Ihnen die Auswahl der gewünschten Filter aus der Liste der verfügbaren Filter.

* *Verfügbare Filter*
+
Zeigt die Liste der verfügbaren Filter für das ausgewählte Objekt auf der Registerkarte Eigenschaften an.

* *Ausgewählte Filter*
+
Zeigt die Liste der aus den verfügbaren Filtern ausgewählten Filter an.

* *Auswahltasten*
+
Ermöglicht das Verschieben des ausgewählten Eintrags von einem Feld in ein anderes.





== Registerkarte Attribute zurückgegeben

Hier können Sie die Details der verfügbaren Filter anzeigen, die erforderlichen Attribute der verfügbaren Filter auswählen und die Sortierreihenfolge für die Attribute festlegen.

* *Verfügbar*
+
Zeigt die verfügbaren Filter und die Attribute für die Filter an.

* *Ausgewählt*
+
Zeigt die ausgewählten Filter und die Attribute, die Aliase und die Sortierreihenfolge für die ausgewählten Filter an.

* *Befehlsschaltflächen*
+
** *Auf*
+
Verschiebt den ausgewählten Eintrag eine Zeile in der ausgewählten Tabelle nach oben.

** *Down*
+
Verschiebt den ausgewählten Eintrag in der ausgewählten Tabelle eine Zeile nach unten.

** *Auswahltasten*
+
Verschiebt den ausgewählten Eintrag von einer Tabelle in eine andere.







== Befehlsschaltflächen

* *Test*
+
Ermöglicht das Testen des Finder, den Sie zum Klonen ausgewählt haben.

* *Speichern*
+
Speichert den Finder und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht ggf. Änderungen ab und schließt das Dialogfeld.


