---
permalink: help/reference-clone-dictionary-entry-dialog-box.html 
sidebar: sidebar 
keywords: dictionary, entry, dialog box, enable, copy, object, edit, definition, clone, new 
summary: Das Dialogfeld Neuer Wörterbucheintrag <EntryName_copy> ermöglicht es Ihnen, ein Wörterbuchobjekt zu kopieren und die Definition des geklonten Wörterbuchobjekts zu bearbeiten. 
---
= Dialogfeld „Eintrag des Klonwörterbuchs“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Dialogfeld Neuer Wörterbucheintrag <EntryName_copy> ermöglicht es Ihnen, ein Wörterbuchobjekt zu kopieren und die Definition des geklonten Wörterbuchobjekts zu bearbeiten.

* *Name des Objekttyps*
+
Ermöglicht die Angabe eines Namens für das geklonte Wörterbuchobjekt.

* *Beschreibung*
+
Ermöglicht die Angabe einer Beschreibung für das geklonte Wörterbuchobjekt.

* *Schema*
+
Ermöglicht die Auswahl eines Schemas, das mit dem geklonten Wörterbuchobjekt verknüpft werden soll. Sie können benutzerdefinierte Wörterbucheinträge zu den zertifizierten Schemata hinzufügen.

* *Entity Version*
+
Ermöglicht die Eingabe der Versionsnummer für den Eintrag geklontes Wörterbuch in `major.minor.revision` Format – z. B. 1.0.0.





== Attributtabelle

Hier können Sie eine Liste von Attributen angeben, die das geklonte Wörterbuchobjekt definieren.

* *Name*
+
Ermöglicht die Eingabe des Namens des Attributs.

* *Typ*
+
Hier können Sie den Typ des Attributs auswählen, z. B. String, boolescher Wert und Integer- für die Typüberprüfung. Sie können auch auf einen Wörterbucheintrag aus dem ausgewählten Schema verweisen.

* *String-Länge*
+
Ermöglicht die Angabe der Länge des Strings in Zahlen, wenn für das Attribut der String ausgewählt ist.

* *Werte*
+
Hier können Sie eine Liste mit kommagetrennten Werten angeben, wenn der Enum-Typ für das Attribut ausgewählt ist.

* * Natürlicher Schlüssel*
+
Hier können Sie festlegen, ob das Attribut des Wörterbuchs Teil des natürlichen Schlüssels des Wörterbuchs ist.

+
Ein natürlicher Schlüssel ist die eindeutige Kennung eines Wörterbuchobjekts. Beispielsweise werden qtrees vom qtree-Namen, dem Volume-Namen und der Array-IP-Adresse identifiziert.

* *Gecachte*
+
Hier können Sie festlegen, ob das Attribut zwischengespeichert werden soll.

+
Ein Wörterbucheintrag kann sowohl zwischengespeicherte Attribute als auch Attribute enthalten, die nicht zwischengespeichert werden. Eine Cache-Tabelle wird erstellt und mit den Attributen gefüllt, die während der Cache-Erfassung des Schemas zum Caching markiert sind. Für ein Wörterbuchobjekt wird eine Cache-Tabelle erstellt, wenn mindestens ein Attribut für den Cache ausgewählt ist.

* *Kann null* sein
+
Ermöglicht die Angabe, ob der Wert des Attributs null sein kann. Diese Einstellung ist nur für Attribute gültig, die für den Cache ausgewählt wurden.

* *Beschreibung*
+
Hier können Sie eine Beschreibung für das Attribut angeben.

* *Werte in natürlichen Schlüsselspalten sind Groß- und Kleinschreibung*
+
Ermöglicht die Angabe, dass die natürlichen Schlüssel Groß- und Kleinschreibung beachten.

* *Befehlsschaltflächen*
+
** *Zeile hinzufügen*
+
Ermöglicht das Hinzufügen einer Zeile zur Tabelle, die zum Festlegen eines Attributs verwendet wird.

** *Zeile entfernen*
+
Ermöglicht das Löschen der ausgewählten Zeile.




