---
permalink: help/reference-new-finder-dialog-box.html 
sidebar: sidebar 
keywords: new, finder, dialog box, enable, create 
summary: Im Dialogfeld Neuer Finder können Sie neue Suchgeräte erstellen. 
---
= Neues Dialogfeld „Finder“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Neuer Finder können Sie neue Suchgeräte erstellen.

* Registerkarte Eigenschaften
* Filter
* Registerkarte Attribute zurückgegeben




== Registerkarte Eigenschaften

Über die Registerkarte *Properties* können Sie einen Namen für den Finder angeben, den Typ des WFA Dictionary-Objekts auswählen und eine Beschreibung für den Finder eingeben. Die Registerkarte zeigt auch die Eingabeparameter an, nachdem ein Filter auf der Registerkarte *Filter* ausgewählt wurde.

* *Name*
+
Ermöglicht die Eingabe eines Namens für den Finder.

* *Typ*
+
Ermöglicht Ihnen, den Objekttyp aus der Liste, z. B. Aggregat, Initiatorgruppe und Cluster, auszuwählen. Die Filter für das ausgewählte Objekt werden auf der Registerkarte *Filter* angezeigt.

* *Entity Version*
+
Ermöglicht die Eingabe der Versionsnummer für den Finder in `major.minor.revision` Format – z. B. 1.0.0.

* *Beschreibung*
+
Ermöglicht die Eingabe einer Beschreibung für den Finder.

* *Eingabeparameter-Tabelle*
+
Zeigt die Eingabeparameter für die ausgewählten Filter an.





== Registerkarte Filter

Ermöglicht Ihnen die Auswahl der gewünschten Filter aus der Liste der verfügbaren Filter.

* *Verfügbare Filter*
+
Zeigt die Liste der verfügbaren Filter für das ausgewählte Objekt auf der Registerkarte *Eigenschaften* an.

* *Ausgewählte Filter*
+
Zeigt die Liste der aus den verfügbaren Filtern ausgewählten Filter an.

* *Auswahltasten*
+
Verschiebt den ausgewählten Eintrag von einem Feld in ein anderes.





== Registerkarte Attribute zurückgegeben

Hier können Sie Details zu den verfügbaren Filtern anzeigen, die erforderlichen Attribute der verfügbaren Filter auswählen und die Sortierreihenfolge für die Attribute festlegen.

* *Verfügbar*
+
Zeigt die verfügbaren Filter und die Attribute für die Filter an.

* *Ausgewählt*
+
Zeigt die ausgewählten Filter und die Attribute, die Aliase und die Sortierreihenfolge für die ausgewählten Filter an.

* *Befehlsschaltflächen*
+
** *Auf*
+
Verschiebt den ausgewählten Eintrag eine Zeile in der ausgewählten Tabelle nach oben.

** *Down*
+
Verschiebt den ausgewählten Eintrag in der ausgewählten Tabelle eine Zeile nach unten.

** *Auswahltasten*
+
Verschiebt den ausgewählten Eintrag von einer Tabelle in eine andere.







== Befehlsschaltflächen

* *Test*
+
Ermöglicht das Testen des von Ihnen definierten Finder.

* *Speichern*
+
Speichert den Finder und schließt das Dialogfeld.

* *Abbrechen*
+
Speichert den Finder nicht und schließt das Dialogfeld.


