---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: Im Dialogfeld Neue Anmeldeinformationen können Sie neue Anmeldedaten erstellen. 
---
= Dialogfeld „Neue Anmeldeinformationen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Neue Anmeldeinformationen können Sie neue Anmeldedaten erstellen.



== Anmeldeinformationsparameter

Sie können die folgenden Parameter für die neu erstellten Anmeldedaten festlegen:

* * Match*
+
Ermöglicht Ihnen die Auswahl des Match-Typs der Anmeldeinformationen, der die Anmeldeinformationen für eine bestimmte IP-Adresse oder einen Hostnamen oder einen gesamten Subnetz- oder IP-Bereich definiert. Sie können eine der folgenden Optionen auswählen:

+
** Exact: Definiert Anmeldeinformationen für einen bestimmten IP- oder Hostnamen
** Muster: Definiert Anmeldeinformationen für den Host-Namensbereich oder den gesamten Subnetz- oder IP-Bereich
+
„Muster“ ist ein regulärer Ausdruck, der zum Abgleichen eines Strings verwendet wird. Beispiel: `10.10.10.` Entspricht jeder IP im Bereich 10.10.10.0 bis 10.10.10.255 und `host` Stimmt alle Host-Namen ab, die mit beginnen `host`.



* *Typ*
+
Ermöglicht die Auswahl des Hosttyps aus der Dropdown-Liste.

+

NOTE: VMware vCenter wird für Linux nicht unterstützt.

* *Name/IP*
+
Ermöglicht die Angabe des Host-Namens oder der IP-Adresse für die Anmeldedaten.

* *Benutzername*
+
Ermöglicht die Angabe eines Benutzernamens für die Anmeldedaten.

* *Passwort*
+
Ermöglicht die Angabe eines Passworts für den Benutzernamen, den Sie für die Anmeldedaten erstellt haben.

* *Standardwerte Überschreiben*
+
Ermöglicht es Ihnen, die Standardwerte des Protokolls, Ports und Timeout zu überschreiben, die dem ausgewählten Remote-Systemtyp für die Anmeldedaten zugeordnet sind.

+
Standardmäßig ist dieses Kontrollkästchen nicht aktiviert. Sie müssen das Kontrollkästchen aktivieren, wenn Sie die Standardwerte überschreiben möchten.





== Befehlsschaltflächen

* *Test*
+
Ermöglicht Ihnen, die Verbindung zum Host oder zur IP-Adresse zu testen, indem Sie sich mit den erforderlichen Anmeldedaten anmelden.

* *Speichern*
+
Speichert die Konfigurationseinstellungen und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht ggf. Änderungen ab und schließt das Dialogfeld.


