---
permalink: help/task-configure-a-database-user-by-running-ocsetup-on-linux.html 
sidebar: sidebar 
keywords: run, ocstep, datafabric, manager, server, configure, read-only, access, oncommand, workflow, automation 
summary: Sie können die ocSetup-Datei auf dem DataFabric Manager 5.x-Server ausführen, um schreibgeschützten Zugriff auf die DataFabric Manager 5.x-Datenbank in OnCommand Workflow Automation zu konfigurieren. 
---
= Konfigurieren Sie einen Datenbankbenutzer, indem Sie ocsetup unter Linux ausführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ausführen `ocsetup` Datei auf dem DataFabric Manager 5.x-Server, um schreibgeschützten Zugriff auf die DataFabric Manager 5.x-Datenbank in OnCommand Workflow Automation zu konfigurieren.

.Schritte
. Laden Sie die herunter `wfa_ocsetup.sh` Datei mit dem folgenden Befehl im Terminal in Ihr Home-Verzeichnis auf dem DataFabric Manager 5.x Server:
+
`+wget https://WFA_Server_IP/download/wfa_ocsetup.sh+`

+
_WFA_Server_IP_ ist die IP-Adresse (IPv4 oder IPv6-Adresse) Ihres WFA Servers.

+
Wenn Sie einen nicht-Standardport für WFA angegeben haben, müssen Sie die Portnummer wie folgt angeben:

+
`+wget https://wfa_server_ip:port/download/wfa_ocsetup.sh+`

+
_Port_ ist die TCP-Portnummer, die Sie bei der Installation für den WFA Server verwendet haben.

+
Wenn Sie eine IPv6-Adresse angeben, müssen Sie sie mit eckigen Klammern schließen.

. Verwenden Sie den folgenden Befehl im Terminal, um den zu ändern `wfa_ocsetup.sh` Datei zu einer ausführbaren Datei:
+
 `chmod +x wfa_ocsetup.sh`
. Führen Sie das Skript durch, indem Sie im Terminal Folgendes eingeben:
+
`./wfa_ocsetup.sh OpenJDK_path`

+
_OpenJDK_PATH_ ist der Pfad zu OpenJDK.

+
Beispiel

+
`/opt/NTAPdfm/java`

+
Die folgende Ausgabe wird auf dem Terminal angezeigt, was auf eine erfolgreiche Einrichtung hinweist:

+
[listing]
----
Verifying archive integrity... All good.
Uncompressing WFA OnCommand Setup.....
*** Welcome to OnCommand Setup Utility for Linux ***
    <Help information>
*** Please override the default credentials below ***
Override DB Username [wfa] :
----
. Geben Sie einen Benutzernamen und ein Kennwort ein, um die Standardanmeldeinformationen zu überschreiben.
+
Ein neues Datenbank-Benutzerkonto wird mit Zugriff auf die DataFabric Manager 5.x Datenbank erstellt.

+

NOTE: Wenn Sie kein Benutzerkonto erstellen, werden die Standardanmeldeinformationen verwendet. Aus Sicherheitsgründen müssen Sie ein Benutzerkonto erstellen.

+
Die folgende Ausgabe wird auf dem Terminal angezeigt, was auf eine erfolgreiche Einrichtung hinweist:

+
[listing]
----
***** Start of response from the database *****
>>> Connecting to database
<<< Connected
*** Dropped existing 'wfa' user
=== Created user 'username'
>>> Granting access
<<< Granted access
***** End of response from the database *****
***** End of Setup *****
----

