---
permalink: help/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: configure, oncommand, workflow, automation, use, microsoft, active, directory, lightweight, access, protocol, server, authentication, authorization 
summary: 'Sie können OnCommand Workflow Automation (WFA) konfigurieren, um einen Microsoft Active Directory (AD) LDAP-Server (Lightweight Directory Access Protocol) zur Authentifizierung und Autorisierung zu verwenden.' 
---
= Konfigurieren Sie die Authentifizierungseinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können OnCommand Workflow Automation (WFA) konfigurieren, um einen Microsoft Active Directory (AD) LDAP-Server (Lightweight Directory Access Protocol) zur Authentifizierung und Autorisierung zu verwenden.

*Was Sie brauchen*

Sie müssen einen Microsoft AD LDAP-Server in Ihrer Umgebung konfiguriert haben.

*Über diese Aufgabe*

Für WFA wird nur die Microsoft AD-LDAP-Authentifizierung unterstützt. Sie können keine anderen LDAP-Authentifizierungsmethoden verwenden, einschließlich Microsoft AD Lightweight Directory Services (AD LDS) oder Microsoft Global Catalog.


NOTE: Während der Kommunikation sendet LDAP den Benutzernamen und das Passwort im Klartext. Allerdings ist die Kommunikation mit LDAPS (LDAP Secure) verschlüsselt und sicher.

.Schritte
. Melden Sie sich über einen Webbrowser als Administrator bei WFA an.
. Klicken Sie auf *Einstellungen* und klicken Sie unter *Setup* auf *Authentifizierung*.
. Aktivieren Sie das Kontrollkästchen * Active Directory aktivieren*.
. Geben Sie die erforderlichen Informationen in die folgenden Felder ein:
+
.. *Optional:* Wenn Sie das Format _user@Domain_ für Domain-Benutzer verwenden möchten, ersetzen Sie `sAMAccountName` Mit `userPrincipalName` Im Feld * Benutzername Attribut*.
.. *Optional:* Wenn für Ihre Umgebung eindeutige Werte erforderlich sind, bearbeiten Sie die erforderlichen Felder.
.. Geben Sie die URI des AD-Servers wie folgt ein: + Beispiel: `ldap://active_directory_server_address\[:port\]`
+
`ldap://NB-T01.example.com[:389]`

+
Wenn Sie LDAP über SSL aktiviert haben, können Sie das folgende URI-Format verwenden: `ldaps://active_directory_server_address\[:port\]`

.. Fügen Sie eine Liste mit AD-Gruppennamen der erforderlichen Rollen hinzu.
+

NOTE: Im Fenster „Active Directory Groups“ können Sie den erforderlichen Rollen eine Liste mit AD-Gruppennamen hinzufügen.



. Klicken Sie Auf *Speichern*.

