---
permalink: workflows/concept-how-you-map-command-parameters.html 
sidebar: sidebar 
keywords: parameter, workflow, automation, commands, mapped, specific, attributes, dictionary, entry, references, certain, rules, aware, map, command, create, edit 
summary: 'Die Parameter in den Befehlen Workflow Automation (WFA) werden basierend auf bestimmten Regeln spezifischen Attributen und Referenzen für Glossareintrag zugeordnet. Beim Erstellen oder Bearbeiten eines WFA Befehls müssen Sie die Regeln kennen, um Befehlsparameter zuzuordnen.' 
---
= Zuordnung von Befehlsparametern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Parameter in den Befehlen Workflow Automation (WFA) werden basierend auf bestimmten Regeln spezifischen Attributen und Referenzen für Glossareintrag zugeordnet. Beim Erstellen oder Bearbeiten eines WFA Befehls müssen Sie die Regeln kennen, um Befehlsparameter zuzuordnen.

Über die Befehlsparameter-Zuordnung wird definiert, wie in den Workflows Befehlsdetails definiert werden. Zugeordnete Befehlsparameter eines Befehls werden in Registerkarten angezeigt, wenn Sie die Befehlsdetails für Befehle in Workflows angeben. Die Namen der Registerkarten basieren auf dem Gruppennamen, der in der Spalte Objektname der Registerkarte Parameterzuordnung angegeben ist. Die Parameter, die nicht zugeordnet sind, werden auf der Registerkarte andere Parameter angezeigt, wenn Sie die Befehlsdetails in Workflows angeben.

Die Regeln für die Befehlsparameter-Zuordnung werden basierend auf der Befehlskategorie und der Darstellung der Befehle im Workflow-Editor angewendet.

Im Folgenden sind die Befehlskategorien:

* Befehle, die Objekte erstellen
* Befehle, die Objekte aktualisieren
* Befehle, die Objekte entfernen
* Befehle, die optionale übergeordnete und untergeordnete Objekte enthalten
* Befehle, die Zuordnungen zwischen Objekten aktualisieren


Die Regeln für jede Kategorie sind unten aufgeführt:



== Alle Befehlskategorien

Beim Zuordnen eines Befehlsparameters sollten Sie den natürlichen Pfad verwenden, basierend auf der Verwendung des Befehls in Workflows.

Die folgenden Beispiele zeigen, wie Sie einen natürlichen Pfad definieren können:

* Für den Parameter ArrayIP sollten Sie je nach Befehl das Attribut Aggregate.Array.ip des Eintrags Volume dictionary und nicht das Attribut Array.ip verwenden.
+
Das ist wichtig, wenn ein Workflow ein Volume erstellt und dann mit dem erstellten Volume einen zusätzlichen Schritt weiterführt. Im Folgenden finden Sie ähnliche Beispiele:

+
** Volume.Aggregate.Array.ip des Eintrags aus dem Qtree Wörterbuch
** Volume.Aggregate.Array.ip des Eintrags des LUN-Wörterbuchs


* Für Cluster, die in Befehlen verwendet werden, sollten Sie einen der folgenden verwenden:
+
** vserver.Cluster.primary_address des Volume Dictionary -Eintrags
** Volume.vserver.Cluster.primary_address des Eingabe vom Qtree-Wörterbuch






== Befehle, die Objekte erstellen

Diese Befehlskategorie wird für eine der folgenden Befehle verwendet:

* Suchen eines übergeordneten Objekts und Definieren neuer Objekte
* Sucht nach einem Objekt und erstellt das Objekt, wenn das Objekt nicht vorhanden ist


Sie sollten für diese Befehlskategorie die folgenden Parameterzuordnungsregeln verwenden:

* Ordnen Sie die relevanten Parameter des Objekts dem Wörterbucheintrag des Objekts zu.
* Ordnen Sie das übergeordnete Objekt anhand der Referenzen des erstellten Wörterbucheintrags zu.
* Beim Hinzufügen eines neuen Parameters muss das entsprechende Attribut im Glossareintrag vorhanden sein.
+
Die folgenden Ausnahmeszenarien gelten für diese Regel:

+
** Einige erstellte Objekte haben keinen entsprechenden Wörterbucheintrag und nur das übergeordnete Objekt ist dem entsprechenden Eintrag des übergeordneten Wörterbuchs zugeordnet, zum Beispiel dem Befehl *VIF erstellen*, in dem lediglich ein Array dem Eintrag des Array-Wörterbuchs zugeordnet werden kann.
** Die Parameterzuordnung ist nicht erforderlich
+
Der Parameter ExecutionTimeout im Befehl *Erstellen oder Ändern der Größe von Aggregat* ist beispielsweise ein nicht auswählbares Parameter.





Folgende zertifizierte Befehle sind Beispiele für diese Kategorie:

* Volume erstellen
* LUN erstellen




== Befehle, die Objekte aktualisieren

Diese Befehlskategorie wird verwendet, um ein Objekt zu finden und die Attribute zu aktualisieren.

Sie sollten für diese Befehlskategorie die folgenden Parameterzuordnungsregeln verwenden:

* Ordnen Sie die Objekte zu, die dem Eintrag des Wörterbuchs aktualisiert werden.
* Ordnen Sie die Parameter, die für das Objekt aktualisiert werden, nicht zu.
+
Im Befehl *Set Volume State* wird beispielsweise der Parameter Volume zugeordnet, der neue Status wird jedoch nicht zugeordnet.





== Befehle, die Objekte entfernen

Diese Befehlskategorie wird verwendet, um ein Objekt zu finden und zu löschen.

Sie sollten das Objekt, das vom Befehl gelöscht wird, seinem Wörterbucheintrag zuordnen. Im Befehl *Volume entfernen* wird das zu löschende Volume beispielsweise den entsprechenden Attributen und Referenzen des Volume-Wörterbuchs zugeordnet.



== Befehle, die optionale übergeordnete und untergeordnete Objekte enthalten

Sie sollten für diese Befehlskategorie die folgenden Parameterzuordnungsregeln verwenden:

* Ordnen Sie einen obligatorischen Parameter eines Befehls nicht als Referenz von einem optionalen Parameter des Befehls zu.
+
Diese Regel ist relevanter, wenn ein Befehl optionale untergeordnete Objekte eines bestimmten übergeordneten Objekts behandelt. In diesem Fall sollte das untergeordnete und das übergeordnete Objekt explizit zugeordnet werden. Zum Beispiel stoppt der Befehl *Deduplication Jobs* einen laufenden Deduplizierungsauftrag auf einem bestimmten Volume, wenn er zusammen mit Array oder auf allen Volumes des angegebenen Arrays angegeben wird. In diesem Fall sollte der Array-Parameter direkt dem Eintrag des Array-Wörterbuchs zugeordnet werden und nicht Volume.Array, da Volume ein optionaler Parameter in diesem Befehl ist.

* Wenn eine übergeordnete und untergeordnete Beziehung zwischen Wörterbucheinträgen auf logischer Ebene, jedoch nicht zwischen den eigentlichen Instanzen in einem bestimmten Befehl besteht, sollten diese Objekte separat zugeordnet werden.
+
Im Befehl *Move Volume* wird zum Beispiel das Volume von seinem aktuellen übergeordneten Aggregat in ein neues Zielaggregat verschoben. Daher werden Volume-Parameter einem Volume-Wörterbuch-Eintrag zugeordnet, und die Zielaggregatparameter werden separat dem Eintrag Aggregate-Wörterbuch zugeordnet, jedoch nicht als volume.aggregate.name.





== Befehle, die Zuordnungen zwischen Objekten aktualisieren

Für diese Kategorie von Befehlen sollten Sie sowohl die Verknüpfung als auch die Objekte den entsprechenden Wörterbucheinträgen zuordnen. Im Befehl Volume zu vFiler hinzufügen werden beispielsweise die Parameter Volume und vFiler den entsprechenden Attributen der Wörterbucheinträge des Volumes und vFiler zugeordnet.
