---
permalink: workflows/reference-perl-database-modules-bundled-with-windows.html 
sidebar: sidebar 
keywords: perl, modules, bundle, windows, active, state, distribution, oncommand, workflow, automation, use, code, writing, commands 
summary: 'Einige Perl-Module werden mit der Windows Active State Perl Distribution for OnCommand Workflow Automation (WFA) gebündelt. Sie können diese Perl-Module in Ihrem Perl-Code zum Schreiben von Befehlen verwenden, nur wenn sie mit Windows gebündelt sind.' 
---
= Perl-Module mit Windows gebündelt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Einige Perl-Module werden mit der Windows Active State Perl Distribution for OnCommand Workflow Automation (WFA) gebündelt. Sie können diese Perl-Module in Ihrem Perl-Code zum Schreiben von Befehlen verwenden, nur wenn sie mit Windows gebündelt sind.

In der folgenden Tabelle sind die Perl-Datenbankmodule aufgeführt, die mit Windows für WFA gebündelt sind.

[cols="2*"]
|===
| Datenbankmodul | Beschreibung 


 a| 
DBD::mysql
 a| 
Perl5-Datenbank-Schnittstellentreiber, mit dem Sie eine Verbindung zur MySQL-Datenbank herstellen können.



 a| 
Versuchen Sie::Winzig
 a| 
Minimiert häufige Fehler durch Evaluierungsblöcke.



 a| 
XML::LibXML
 a| 
Schnittstelle zu libxml2, die XML- und HTML-Parser mit DOM-, SAX- und XMLReader-Schnittstellen bereitstellt.



 a| 
DBD::Cassandra
 a| 
Perl5-Datenbanktreiber für Cassandra, der die CQL3-Abfragesprache verwendet.

|===