---
permalink: workflows/task-update-the-pack-from-scm.html 
sidebar: sidebar 
keywords: update, pack, source, control, management, server, import, oncommand, workflow, automation 
summary: 'Sie können ein Paket im SCM Server (Source Control Management) aktualisieren und das aktualisierte Paket nach OnCommand Workflow Automation (WFA) importieren.' 
---
= Aktualisieren der WFA Workflow Packs vom SCM Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Paket im SCM Server (Source Control Management) aktualisieren und das aktualisierte Paket nach OnCommand Workflow Automation (WFA) importieren.

.Was Sie benötigen
Das SCM muss eingerichtet sein und Sie müssen über Administrator- oder Architekturdaten verfügen

.Über diese Aufgabe
Wenn Sie Änderungen oder Aktualisierungen an einem Paket im SCM-Server vornehmen, müssen der Administrator oder Architekt die Konflikte gegebenenfalls mit Hilfe der SCM-bereitgestellten Diff-Tools lösen. WFA dient zur Abschneide der XML diff-Datei, um nur die relevanten Änderungen anzuzeigen.

Vor dem Importieren des Packs werden Sie über die Änderungen in den WFA Pack-Inhalt informiert.

.Schritte
. Melden Sie sich über einen Webbrowser im WFA Fenster an.
. Importieren Sie das aktualisierte Paket zu WFA.
+
link:task-import-an-oncommand-workflow-automation-pack.html["WFA Workflow Packs importieren"]

+

NOTE: Wenn die WFA Datenbank bereits das gleiche Paket enthält, wird der Inhalt des Packs überschrieben.


