---
permalink: workflows/task-import-oncommand-workflow-automation-content.html 
sidebar: sidebar 
keywords: import, user-created, oncommand, workflow, automation, content, finders, commands, export, installation, downloaded, storage, community, pack, data, pwershell, toolkits, perl 
summary: 'Sie können WFA Inhalte (User-created OnCommand Workflow Automation) wie Workflows, Finder und Befehle importieren. Sie können auch Inhalte importieren, die von einer anderen WFA Installation exportiert werden, Inhalte, die aus dem Storage Automation Store oder der WFA Community heruntergeladen werden, sowie Pakete einschließlich Data ONTAP PowerShell Toolkits und Perl NMSDK Toolkits.' 
---
= Importieren Sie OnCommand Workflow Automation-Inhalte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können WFA Inhalte (User-created OnCommand Workflow Automation) wie Workflows, Finder und Befehle importieren. Sie können auch Inhalte importieren, die von einer anderen WFA Installation exportiert werden, Inhalte, die aus dem Storage Automation Store oder der WFA Community heruntergeladen werden, sowie Pakete einschließlich Data ONTAP PowerShell Toolkits und Perl NMSDK Toolkits.

.Was Sie benötigen
* Sie benötigen Zugriff auf den WFA Inhalt, den Sie importieren möchten.
* Der zu importierende Inhalt muss auf einem System erstellt worden sein, das dieselbe oder eine frühere Version von WFA ausführt.
+
Wenn beispielsweise WFA 2.2 ausgeführt wird, können Sie keine Inhalte importieren, die mit WFA 3.0 erstellt wurden.

* Sie können in N-2-Versionen von WFA entwickelte Inhalte nur in WFA 5.1 importieren.
* Wenn der `.dar` Dateireferenzen NetApp zertifizierte Inhalte; NetApp zertifizierte Content Packs müssen importiert werden.
+
Die NetApp zertifizierten Content Packs können im Storage Automation Store heruntergeladen werden. Überprüfen Sie in der Dokumentation des Pakets, ob alle Anforderungen erfüllt sind.



.Schritte
. Melden Sie sich über einen Webbrowser bei WFA an.
. Klicken Sie auf *Einstellungen* und klicken Sie unter *Wartung* auf *Workflows importieren*.
. Klicken Sie auf *Datei auswählen*, um das auszuwählen `.dar` Datei, die Sie importieren möchten, und klicken Sie dann auf *Import*.
. Klicken Sie im Dialogfeld *Erfolg importieren* auf *OK*.

